/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiLiveEventsRouteImport } from './routes/api/live-events'
import { Route as ApiLiveStreamRouteImport } from './routes/api/live-stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveEventsRoute = ApiLiveEventsRouteImport.update({
  id: '/api/live-events',
  path: '/api/live-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveStreamRoute = ApiLiveStreamRouteImport.update({
  id: '/api/live-stream',
  path: '/api/live-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/live-events': typeof ApiLiveEventsRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/live-events': typeof ApiLiveEventsRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/live-events': typeof ApiLiveEventsRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/analyze' | '/api/ask' | '/api/live-events' | '/api/live-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api/analyze' | '/api/ask' | '/api/live-events' | '/api/live-stream'
  id:
    | '__root__'
    | '/'
    | '/api/analyze'
    | '/api/ask'
    | '/api/live-events'
    | '/api/live-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiLiveEventsRoute: typeof ApiLiveEventsRoute
  ApiLiveStreamRoute: typeof ApiLiveStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-events': {
      id: '/api/live-events'
      path: '/api/live-events'
      fullPath: '/api/live-events'
      preLoaderRoute: typeof ApiLiveEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-stream': {
      id: '/api/live-stream'
      path: '/api/live-stream'
      fullPath: '/api/live-stream'
      preLoaderRoute: typeof ApiLiveStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiAskRoute: ApiAskRoute,
  ApiLiveEventsRoute: ApiLiveEventsRoute,
  ApiLiveStreamRoute: ApiLiveStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
